### ISSUE TITLE
"An error has occurred" message

### ISSUE THREAD

**Issue by MidnightRetro** [usefulstuffs/Driver-Easy-Loader#1]
I had used the old loader with Driver Easy 5.something, and it worked except for the speed limit.
Today I uninstalled Driver Easy, installed version 6.0, ran the new loader 2.0, but I got an error message and the patch fails.

**Comment by MidnightRetro** [comment]
BTW, the old loader works on 6.0 but has the speed limit still

**Comment by usefulstuffs** [comment]
Didn't test with 6.0 of driver easy. Probably it's related to the modification of the hosts file to block Driver Easy from reaching its servers.

**Comment by usefulstuffs** [comment]
#2 Please use now 1.2 instead

**Comment by MidnightRetro** [comment]
Thank you. I tried 1.3 and it works BUT it has the speed limit...

**Comment by usefulstuffs** [comment]
> Thank you. I tried 1.3 and it works BUT it has the speed limit...

There is no way to avoid it as the speed is controlled by Driver Easy's servers
