### ISSUE TITLE
It doesn't work anymore with the latest update

### ISSUE THREAD

**Issue by frostee81** [usefulstuffs/Driver-Easy-Loader#2]
As title says now there is this:

![Screenshot 2024-07-10 182549](https://github.com/usefulstuffs/Driver-Easy-Loader/assets/121062276/516328ff-1224-4e0d-afb2-c0c42b9fbdfa)

**Comment by usefulstuffs** [comment]
Well, in this case just use the 1.x version

**Comment by usefulstuffs** [comment]
I checked out and the 1.2 method is still working, so you may want to use that instead. I will make a 1.3 release soon reverting 2.0

**Comment by frostee81** [comment]
Thanks. It's working now. Life saver.
